name: Backend CI workflow

# trigger this workflow for backend and main branches
# on push and pull request actions
# when there are changes within backend/ directory
on:
  push:
    branches: 
      - main 
      - backend
    paths:
        - "backend/**"
  pull_request:
    branches:
      - main 
      - backend
    paths:
        - "backend/**"

# environment variables for all steps in workflow
env:
  NODE_ENV: ci

# Defaults for all *RUN* steps in all jobs
defaults:
  run:
    shell: bash
    working-directory: backend

jobs:

  setup-db-and-run-tests:
    name: Start and seed containerized postgres service, start server and run tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x, 17.x]  # https://nodejs.org/en/about/releases/

    steps:
      # Start containerized postgres service from Docker image
      - name: start database
        run: npm run database:start

      - name: create schema in database
        run: npm run database:create-schema
    
      # Downloads a copy of repository before running CI tests
      - name: checkout git repo  
        uses: actions/checkout@v2

      # run steps using each different node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2  
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci
        
        # server makes cn to local containerized db service
      - name: Start server
        run: npm run server
        
        # run tests in separate shell
      - name: Execute tests
        run: npm test

      - name: shutdown database
        run: npm database:stop
